part of 'release_artifacts_test.dart';

void _registerReleaseArtifactsCommandTests() {
  test('documents command design in both languages', () {
    final commands = File('doc/commands.md').readAsStringSync();
    final chineseCommands = File('doc/commands.zh-CN.md').readAsStringSync();

    expectContainsAll(commands, [
      '# Command Design',
      '[简体中文](commands.zh-CN.md)',
      'End-to-End Workflows',
      'AI-driven support is the primary end-to-end path',
      'AI-Driven Support',
      'Add FlutterOH Support to an App Project Manually',
      'skills/fluoh',
      'Run `fluoh skill --path`',
      'printed path',
      'helper scripts',
      'report templates',
      'fluoh upgrade',
      'install the printed path as the fluoh skill',
      'https://github.com/FlutterOH/fluoh/tree/main/skills/fluoh',
      'not installed yet',
      'Use \$fluoh to install fluoh if needed and add FlutterOH support to this Flutter project.',
      'Use \$fluoh to port <upstream-git-url> for FlutterOH, SDK 3.35.',
      'Use \$fluoh to continue implementing FlutterOH support for <package-name>.',
      'Use \$fluoh to precheck this FlutterOH Source change.',
      'read-only preflight',
      'present the final',
      'scope for user approval',
      'separate maintainer decisions',
      'skills/fluoh/SKILL.md',
      'skills/fluoh/references/',
      'fluoh help [command]',
      'fluoh skill',
      'lib/src/cli/skill_command.dart',
      'SDK & Metadata',
      'Project',
      'Package',
      'Workflow',
      'Devices',
      'fluoh clean',
      'lib/src/workflow/commands/clean_command.dart',
      '`skill`, `doctor`, `flutter`, and `upgrade`',
      'fluoh create [--sdk <version-or-series>] <args>',
      'lib/src/project/create_command.dart',
      'fluoh deps',
      'lib/src/deps/commands/deps_command.dart',
      'lib/src/deps/commands/deps_get_command.dart',
      'lib/src/deps/commands/dependency_plan_commands.dart',
      'lib/src/deps/commands/deps_upgrade_command.dart',
      'fluoh plan app',
      'fluoh plan package',
      'lib/src/workflow/commands/plan_command.dart',
      '| `fluoh verify` | `lib/src/workflow/commands/verify_command.dart` |',
      '| `fluoh build <platform>` | `lib/src/workflow/commands/build_command.dart` |',
      '| `fluoh run <platform>` | `lib/src/workflow/commands/run_command.dart` |',
      '| `fluoh attach <platform>` | `lib/src/workflow/commands/attach_command.dart` |',
      '| `fluoh drive <platform>` | `lib/src/workflow/commands/drive_command.dart` |',
      'fluoh flutter <args>',
      'fluohf <args>',
      'fluoh source list',
      'fluoh source stats [--sdk <version-or-line>]',
      'fluoh source enable <name> <url-or-path>',
      'fluoh source disable <name>',
      'fluoh source update [name]',
      'fluoh source register <package-repo>',
      'fluoh source sync [path]',
      'fluoh source check [source]',
      '--schema-only',
      'changedFiles',
      '--skip-release-checks',
      'SDK-only root',
      'fluoh sdk list',
      'fluoh sdk current',
      'fluoh sdk use <version-or-series>',
      '--no-init-ohos',
      'fluoh deps upgrade',
      'fluoh package list',
      'fluoh package new <name>',
      'fluoh package port <upstream>',
      'fluoh package discover <upstream>',
      '--repository-name',
      '--plan',
      'fluoh package add <package-path>',
      'fluoh package upstream check',
      'fluoh package upstream sync',
      'fluoh package scope',
      'fluoh package next',
      'Package implementation work is',
      'next` owns spec review',
      'package next --package <name> --json',
      'fluoh package status',
      'fluoh package handoff',
      'fluoh package version',
      'Package generated `FLUOH.md` context',
      'doc/fluoh/<package>/spec.md',
      'generated `FLUOH.md`',
      'context file is rewritten',
      'package-spec-template.md',
      'release history is kept',
      'doc/fluoh/<package>/scope.yaml',
      'fluoh verify',
      'fluoh build ohos --auto-sign --json',
      'fluoh run ohos --auto-emulator',
      'fluoh run ohos --device-id <id>',
      'fluoh attach <platform>',
      'fluoh build <platform>',
      'linux.build_failed',
      'web.build_failed',
      'windows.build_failed',
      '--no-codesign',
      'integration_test',
      'doc/fluoh/<package>/scenarios',
      'interaction-scenario-template.md',
      'VM Service URI',
      '--session-file <path>',
      '--require-vm-service',
      'flutterRunSession',
      'No interaction required',
      'Runtime permissions require',
      'Run-smoke success',
      'automation.coveragePolicy',
      'fluoh report create',
      'lib/src/workflow/commands/report_command.dart',
      '`scenarioCoverage`',
      '`coverageSummary`',
      '`inventory`',
      '`qualityGates`',
      '`repairLoop`',
      '`FLUOH_IOS_PERMISSION_DRIVER`',
      'emulator or simulator',
      '--auto-sign',
      'fluoh devices',
      'fluoh emulators',
      'nextCommand',
      'diagnostics',
      'fluoh doctor --platform ohos --project --json --strict',
      '.fluoh/tasks',
      'fluoh doctor',
      'fluoh package check',
      'fluoh package release',
      'fluoh doctor',
      '--strict',
      '\$FLUOH_HOME/sources.lock.json',
      'load-index API',
      'Package branch-local `doc/fluoh/<package>/spec.md`',
      'maintained by maintainer/AI',
      'generated spec TODOs',
      'package spec template placeholders',
      '`spec-review`',
      'branch-local spec',
      'pubspec',
      'missing `<package>_ohos` implementation package',
      'file is regenerated',
    ]);
    expectContainsNone(commands, [
      'fluoh source package',
      'fluoh source use',
      'source_pr_review.py',
    ]);

    expectContainsAll(chineseCommands, [
      '# 命令设计',
      '[English](commands.md)',
      '端到端工作流',
      'AI 驱动支持是主要端到端链路',
      'AI 驱动支持',
      '手动为 App 项目增加 FlutterOH 支持',
      'skills/fluoh',
      '运行 `fluoh skill --path`',
      '打印的路径',
      '辅助脚本',
      '报告模板',
      'fluoh upgrade',
      '把打印的路径安装为 fluoh skill',
      'https://github.com/FlutterOH/fluoh/tree/main/skills/fluoh',
      '尚未安装 fluoh',
      '使用 \$fluoh，必要时先安装 fluoh，然后为当前 Flutter 项目增加 FlutterOH 支持。',
      '使用 \$fluoh，按 SDK 3.35 将 <upstream-git-url> 移植为 FlutterOH Package。',
      '使用 \$fluoh，继续为 <package-name> 实现 FlutterOH 支持。',
      '使用 \$fluoh，预检查这个 FlutterOH Source 变更。',
      '只读 preflight',
      '展示最终范围',
      '等待用户确认',
      '单独的维护者决策',
      'skills/fluoh/SKILL.md',
      'skills/fluoh/references/',
      'fluoh help [command]',
      'fluoh skill',
      'lib/src/cli/skill_command.dart',
      'SDK & Metadata',
      'Project',
      'Package',
      'Workflow',
      'Devices',
      'fluoh clean',
      'lib/src/workflow/commands/clean_command.dart',
      '`skill`、`doctor`、`flutter`',
      'fluoh create [--sdk <version-or-series>] <args>',
      'lib/src/project/create_command.dart',
      'fluoh deps',
      'lib/src/deps/commands/deps_command.dart',
      'lib/src/deps/commands/deps_get_command.dart',
      'lib/src/deps/commands/dependency_plan_commands.dart',
      'lib/src/deps/commands/deps_upgrade_command.dart',
      'fluoh plan app',
      'fluoh plan package',
      'lib/src/workflow/commands/plan_command.dart',
      '| `fluoh verify` | `lib/src/workflow/commands/verify_command.dart` |',
      '| `fluoh build <platform>` | `lib/src/workflow/commands/build_command.dart` |',
      '| `fluoh run <platform>` | `lib/src/workflow/commands/run_command.dart` |',
      '| `fluoh attach <platform>` | `lib/src/workflow/commands/attach_command.dart` |',
      '| `fluoh drive <platform>` | `lib/src/workflow/commands/drive_command.dart` |',
      'fluoh flutter <args>',
      'fluohf <args>',
      'fluoh source list',
      'fluoh source stats [--sdk <version-or-line>]',
      'fluoh source enable <name> <url-or-path>',
      'fluoh source disable <name>',
      'fluoh source update [name]',
      'fluoh source register <package-repo>',
      'fluoh source sync [path]',
      'fluoh source check [source]',
      '--schema-only',
      'changedFiles',
      '--skip-release-checks',
      'SDK-only 根',
      'fluoh sdk list',
      'fluoh sdk current',
      'fluoh sdk use <version-or-series>',
      '--no-init-ohos',
      'fluoh deps upgrade',
      'fluoh package list',
      'fluoh package new <name>',
      'fluoh package port <upstream>',
      'fluoh package discover <upstream>',
      '--repository-name',
      '--plan',
      'fluoh package add <package-path>',
      'fluoh package upstream check',
      'fluoh package upstream sync',
      'fluoh package scope',
      'fluoh package next',
      '`package next` 通过 `nextAction` 负责 spec review',
      'package next --package <name> --json',
      'fluoh package status',
      'fluoh package handoff',
      'fluoh package version',
      'Package 生成的 `FLUOH.md` 上下文',
      'doc/fluoh/<package>/spec.md',
      'package-spec-template.md',
      '重写时会保留已有 release history',
      'doc/fluoh/<package>/scope.yaml',
      'fluoh verify',
      'fluoh build ohos --auto-sign --json',
      'fluoh run ohos --auto-emulator',
      'fluoh run ohos --device-id <id>',
      'fluoh attach <platform>',
      'fluoh build <platform>',
      'linux.build_failed',
      'web.build_failed',
      'windows.build_failed',
      '--no-codesign',
      'integration_test',
      'doc/fluoh/<package>/scenarios',
      'interaction-scenario-template.md',
      'VM Service URI',
      '--session-file <path>',
      '--require-vm-service',
      'flutterRunSession',
      'No interaction required',
      'runtime permission 需要',
      'run-smoke 成功',
      'automation.coveragePolicy',
      'fluoh report create',
      'lib/src/workflow/commands/report_command.dart',
      '`scenarioCoverage`',
      '`coverageSummary`',
      '`inventory`',
      '`qualityGates`',
      '`repairLoop`',
      '`FLUOH_IOS_PERMISSION_DRIVER`',
      'target',
      '--auto-sign',
      'fluoh devices',
      'fluoh emulators',
      'nextCommand',
      'diagnostics',
      'fluoh doctor --platform ohos --project --json --strict',
      '.fluoh/tasks',
      'fluoh doctor',
      'fluoh package check',
      'fluoh package release',
      'fluoh doctor',
      '--strict',
      '\$FLUOH_HOME/sources.lock.json',
      'load-index API',
      '所选 Package',
      '生成 spec 里的 TODO',
      'Package spec 模板占位符',
      '`spec-review`',
      'branch-local spec',
      'pubspec 重写',
      '`FLUOH.md` Package 上下文',
      '`<package>_ohos`',
      '其余内容全量重新生成',
    ]);
    expectContainsNone(chineseCommands, [
      'fluoh source package',
      'fluoh source use',
      'source_pr_review.py',
    ]);
  });

  test('provides a Homebrew formula backed by native executables', () {
    final formula = File('Formula/fluoh.rb').readAsStringSync();

    expect(formula, contains('class Fluoh < Formula'));
    expect(
      formula,
      contains('https://pub.dev/api/archives/fluoh-0.1.0.tar.gz'),
    );
    expect(formula, contains('sha256 :no_check'));
    expect(formula, contains('depends_on "dart-sdk" => :build'));
    expect(formula, contains('"dart", "pub", "get"'));
    expect(formula, contains('"dart", "compile", "exe", "bin/fluoh.dart"'));
    expect(formula, contains('"dart", "compile", "exe", "bin/fluohf.dart"'));
    expect(formula, isNot(contains('"dart", "pub", "global", "activate"')));
    expect(formula, isNot(contains('pub_cache/"bin/fluoh"')));
    expect(formula, contains('fluoh --version'));
    expect(formula, contains('fluohf --help'));
  });
}
