part of 'release_artifacts_test.dart';

void _registerReleaseArtifactsDocsTests() {
  test('documents public README entry points in both languages', () {
    final readme = File('README.md').readAsStringSync();
    final chineseReadme = File('README.zh-CN.md').readAsStringSync();
    final readmeHero = File(
      'doc/assets/svg/readme-hero.svg',
    ).readAsStringSync();
    final chineseReadmeHero = File(
      'doc/assets/svg/readme-hero.zh-CN.svg',
    ).readAsStringSync();
    final contributing = File('CONTRIBUTING.md').readAsStringSync();
    final chineseContributing = File(
      'CONTRIBUTING.zh-CN.md',
    ).readAsStringSync();

    expectContainsAll(readme, [
      'href="README.zh-CN.md">简体中文',
      'href="skills/fluoh/SKILL.md">Skill',
      'href="doc/commands.md">Commands',
      'href="doc/schema.md">Schema',
      'href="CONTRIBUTING.md">Contributing',
      'AI%20skill-skills%2Ffluoh',
      'FlutterOH-first AI workflows for Flutter apps and packages.',
      'fluoh AI support prompt preview',
      '## Quick Start',
      '### AI First',
      '### Install fluoh',
      '### Existing Flutter App',
      '### New Flutter App',
      '### Package Maintainers',
      'Run `fluoh skill --path`, install the printed path as the fluoh skill',
      'Use https://github.com/FlutterOH/fluoh/tree/main/skills/fluoh only when fluoh is not installed yet.',
      'Use \$fluoh to install fluoh if needed and add FlutterOH support to this Flutter project.',
      'Use \$fluoh to port <upstream-git-url> for FlutterOH.',
      'Use \$fluoh to continue implementing FlutterOH support for <package-name>.',
      'Use \$fluoh to precheck this FlutterOH Source change.',
      'fluoh package next --package <name>',
      'fluoh package status --package <name>',
      'fluoh package queue <package-path>...',
      'fluoh package add <package-path>',
      'dart pub global activate fluoh',
      'cd path/to/existing_app',
      'fluoh create --sdk 3.35 demo_app --platforms=android,ios,ohos',
      'cd demo_app',
      'brew tap FlutterOH/fluoh https://github.com/FlutterOH/fluoh.git',
      'brew install FlutterOH/fluoh/fluoh',
      'fluoh sdk use 3.35 --pub-get',
      'fluoh deps check',
      'fluoh deps fix --dry-run',
      'fluoh deps fix',
      'fluoh deps get',
      'fluoh doctor --platform ohos --project',
      'fluoh build ohos --auto-sign',
      'Create a spec-first FlutterOH package repository',
      'fluoh package new <name> --repository-name <flutteroh-repo-name>',
      'fluoh package port <upstream-git-url> --repository-name <flutteroh-repo-name>',
      'fluoh package discover',
      'fluoh package queue',
      'fluoh package add',
      'fluoh source register . --source <source-repo>',
      'fluoh package next',
      'fluoh package status',
      'fluohf pub get',
      'fluohf run',
      'fluohf build hap',
      'https://github.com/FlutterOH/source.git',
      '[Command reference](doc/commands.md)',
      '[Source schema](doc/schema.md)',
      '[Contributing and release workflow](CONTRIBUTING.md)',
    ]);
    expectContainsNone(readme, [
      'fluoh source package',
      'fluoh source use',
      '--repository git@github.com:FlutterOH/package.git',
      'dart pub publish --dry-run',
      'git tag v0.1.0',
      'doc/ai- support',
      '## Why fluoh',
      '## AI Workflows',
      '## Common Workflows',
      '### Daily Loop',
      '## Maintenance Workflows',
      '--no-init-ohos',
      '--json',
      'fluoh drive all',
      'bundled skill path',
      'update instructions',
      'fluoh upgrade',
    ]);
    expect(readme, isNot(contains('brew tap FlutterOH/tap')));
    expect(
      readme.indexOf('### AI First'),
      lessThan(readme.indexOf('### Install fluoh')),
    );

    expectContainsAll(chineseReadme, [
      'href="README.md">English',
      'href="skills/fluoh/SKILL.md">Skill',
      'href="doc/commands.zh-CN.md">命令',
      'href="doc/schema.zh-CN.md">Schema',
      'href="CONTRIBUTING.zh-CN.md">贡献指南',
      'AI%20skill-skills%2Ffluoh',
      '面向 Flutter App 和 Package 的 FlutterOH 优先 AI 工作流',
      'fluoh AI 支持提示预览',
      '## 快速开始',
      '### AI 优先',
      '### 安装 fluoh',
      '### 已有 Flutter App',
      '### 新建 Flutter App',
      '### Package 维护者',
      '运行 `fluoh skill --path`，把打印的路径安装为 fluoh skill',
      '仅在尚未安装 fluoh 时，才使用 https://github.com/FlutterOH/fluoh/tree/main/skills/fluoh 作为初始来源。',
      '使用 \$fluoh，必要时先安装 fluoh，然后为当前 Flutter 项目增加 FlutterOH 支持。',
      '使用 \$fluoh，将 <upstream-git-url> 移植为 FlutterOH Package。',
      '使用 \$fluoh，继续为 <package-name> 实现 FlutterOH 支持。',
      '使用 \$fluoh，预检查这个 FlutterOH Source 变更。',
      'fluoh package next --package <name>',
      'fluoh package status --package <name>',
      'fluoh package queue <package-path>...',
      'fluoh package add <package-path>',
      'dart pub global activate fluoh',
      'cd path/to/existing_app',
      'fluoh create --sdk 3.35 demo_app --platforms=android,ios,ohos',
      'cd demo_app',
      'brew tap FlutterOH/fluoh https://github.com/FlutterOH/fluoh.git',
      'brew install FlutterOH/fluoh/fluoh',
      'fluoh sdk use 3.35 --pub-get',
      'fluoh deps check',
      'fluoh deps fix --dry-run',
      'fluoh deps fix',
      'fluoh deps get',
      'fluoh doctor --platform ohos --project',
      'fluoh build ohos --auto-sign',
      '可以先基于 spec 新建 FlutterOH Package 仓库',
      'fluoh package new <name> --repository-name <flutteroh-repo-name>',
      'fluoh package port <upstream-git-url> --repository-name <flutteroh-repo-name>',
      'fluoh package discover',
      'fluoh package queue',
      'fluoh package add',
      'fluoh source register . --source <source-repo>',
      'fluoh package next',
      'fluoh package status',
      'fluohf pub get',
      'fluohf run',
      'fluohf build hap',
      'https://github.com/FlutterOH/source.git',
      '[命令参考](doc/commands.zh-CN.md)',
      '[Source schema](doc/schema.zh-CN.md)',
      '[贡献和发布流程](CONTRIBUTING.zh-CN.md)',
    ]);
    expectContainsNone(chineseReadme, [
      'fluoh source package',
      'fluoh source use',
      '--repository git@github.com:FlutterOH/package.git',
      'dart pub publish --dry-run',
      'git tag v0.1.0',
      'doc/ai- support',
      '## 为什么用 fluoh',
      '## AI 工作流',
      '## 常见工作流',
      '### 日常循环',
      '## 维护工作流',
      '--no-init-ohos',
      '--json',
      'fluoh drive all',
      '内置 skill 路径',
      '更新说明',
      'fluoh upgrade',
    ]);
    expect(chineseReadme, isNot(contains('brew tap FlutterOH/tap')));
    expect(
      chineseReadme.indexOf('### AI 优先'),
      lessThan(chineseReadme.indexOf('### 安装 fluoh')),
    );

    expectContainsAll(readmeHero, [
      'fluoh AI support prompt',
      'Tell AI the goal. fluoh runs the workflow.',
      'Apps and packages follow one verified command path.',
      'Use \$fluoh to add FlutterOH support to this project.',
      'install',
      'detect project',
      'pin SDK',
      'fix deps',
      'build/run',
      'save report',
    ]);
    expectContainsAll(chineseReadmeHero, [
      'fluoh AI 支持对话',
      '告诉 AI 目标，fluoh 负责执行。',
      'App 和 Package 都走同一套可验证命令链路。',
      '用 \$fluoh 为当前项目增加 FlutterOH 支持。',
      '安装工具',
      '识别项目',
      '固定 SDK',
      '替换依赖',
      '构建运行',
      '保存报告',
    ]);

    expectContainsAll(contributing, [
      'dart pub publish --dry-run',
      'dart pub global activate --source path . --overwrite',
      'dart pub global activate fluoh --overwrite',
      'dart pub global deactivate fluoh',
      'export PATH="\$HOME/.pub-cache/bin:\$PATH"',
      'Conventional Commits',
      'git tag v0.1.0',
      'brew tap FlutterOH/fluoh https://github.com/FlutterOH/fluoh.git',
      'fluoh package port',
      '--repository https://github.com/FlutterOH/package.git',
      'fluoh package upstream check',
      'fluoh package upstream sync',
      'fluoh verify',
      'fluoh package version',
      'fluoh package release',
      'fluoh source sync',
      'FLUOH.md',
      'FlutterOH Release History',
    ]);
    expectContainsNone(contributing, [
      'feat(implementation)',
      'fluoh source package',
      'gh auth login',
    ]);

    expectContainsAll(chineseContributing, [
      'dart pub publish --dry-run',
      'dart pub global activate --source path . --overwrite',
      'dart pub global activate fluoh --overwrite',
      'dart pub global deactivate fluoh',
      'export PATH="\$HOME/.pub-cache/bin:\$PATH"',
      'Conventional Commits',
      'git tag v0.1.0',
      'brew tap FlutterOH/fluoh https://github.com/FlutterOH/fluoh.git',
      'fluoh package port',
      '--repository https://github.com/FlutterOH/package.git',
      'fluoh package upstream check',
      'fluoh package upstream sync',
      'fluoh verify',
      'fluoh package version',
      'fluoh package release',
      'fluoh source sync',
      'FLUOH.md',
      'FlutterOH Release History',
    ]);
    expectContainsNone(chineseContributing, [
      'feat(implementation)',
      'fluoh source package',
      'gh auth login',
    ]);
  });

  test('documents schema ownership and source file layout', () {
    final schema = File('doc/schema.md').readAsStringSync();
    final chineseSchema = File('doc/schema.zh-CN.md').readAsStringSync();

    expectContainsAll(schema, [
      '# Schema Design',
      '[简体中文](schema.zh-CN.md)',
      'lib/src/schema/',
      '| Project |',
      '| Package |',
      '| Source |',
      '| Manifest |',
      'manifests/<name>/fluoh.yaml',
      'kind: source',
      'kind: manifest',
      'ohos/3.35',
      'repository.git.branch',
      'package.release.version',
      'sdk.kind',
      'platforms.target',
      'publishTargets',
      'upstreamVersion',
      'package.sdks.<sdkLine>.releases',
      '`config.json`',
      '`sources.lock.json`',
      '"fingerprint"',
      '"packageRoutes"',
      'FlutterOH/source',
    ]);
    expectContainsNone(schema, [
      'repository.git.ref',
      'manifests[].packages',
      'repositories/<repository>/fluoh.yaml',
      'CompatibilityMatrix',
      'fluoh_schema',
    ]);

    expectContainsAll(chineseSchema, [
      '# Schema 设计',
      '[English](schema.md)',
      '| Project |',
      '| Package |',
      '| Source |',
      '| Manifest |',
      'manifests/<name>/fluoh.yaml',
      'kind: source',
      'kind: manifest',
      'ohos/3.35',
      'repository.git.branch',
      'package.release.version',
      'sdk.kind',
      'platforms.target',
      'publishTargets',
      'upstreamVersion',
      'package.sdks.<sdkLine>.releases',
      '`config.json`',
      '`sources.lock.json`',
      '"fingerprint"',
      '"packageRoutes"',
      'FlutterOH/source',
    ]);
    expectContainsNone(chineseSchema, [
      'repository.git.ref',
      'manifests[].packages',
      'repositories/<repository>/fluoh.yaml',
      'CompatibilityMatrix',
      'fluoh_schema',
    ]);
  });
}
