import 'dart:convert';
import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:fluoh/fluoh.dart';
import 'package:fluoh/src/cli/terminal_output.dart';
import 'package:fluoh/src/package/commands/package_command.dart';
import 'package:fluoh/src/package/manifest/package_manifest.dart';
import 'package:test/test.dart';

import '../helpers/fluoh_command_context.dart';
import '../helpers/package_test_context.dart';

part 'package_create_core_part.dart';
part 'package_create_core_selection_part.dart';
part 'package_create_docs_part.dart';
part 'package_create_add_part.dart';
part 'package_create_validation_part.dart';

void main() {
  _registerPackageCreateCoreTests();
  _registerPackageCreateCoreSelectionTests();
  _registerPackageCreateDocsTests();
  _registerPackageCreateAddTests();
  _registerPackageCreateValidationTests();
}

class _GuidancePackage {
  const _GuidancePackage({
    required this.name,
    required this.version,
    required this.path,
  });

  final String name;
  final String version;
  final String path;

  String get examplePath => path == '.' ? 'example' : '$path/example';

  String get verifyCommand =>
      path == '.' ? 'fluoh verify' : 'fluoh verify --package $name';

  String get releaseCommand => path == '.'
      ? 'fluoh package release'
      : 'fluoh package release --package $name';

  String get releaseCheckCommand => path == '.'
      ? 'fluoh package check'
      : 'fluoh package check --package $name';

  String get versionCommand => path == '.'
      ? 'fluoh package version'
      : 'fluoh package version --package $name';
}

void _expectReadmeAdaptation(
  String content, {
  required _GuidancePackage package,
}) {
  _expectContainsAll(content, [
    '<!-- fluoh:generated:start id=package-readme-adaptation template=1 -->',
    'This section is generated by fluoh. Do not edit inside this block',
    '## FlutterOH adaptation',
    '[![Latest release](https://img.shields.io/github/v/tag/FlutterOH/',
    '?label=release&sort=date&filter=${package.name}-*)](https://github.com/FlutterOH/',
    'This branch maintains the FlutterOH adaptation for this package.',
    'The original README continues below.',
    '- Metadata: [fluoh.yaml](fluoh.yaml)',
    '- Maintainer guide: [FLUOH.md](FLUOH.md)',
    '- Release notes: [FLUOH_CHANGELOG.md](FLUOH_CHANGELOG.md)',
    '- Validation: `${package.releaseCheckCommand}`',
    '<!-- fluoh:generated:end id=package-readme-adaptation -->',
  ]);
  if (package.path == '.') {
    expect(content, isNot(contains('- Package path:')));
  } else {
    expect(
      content,
      contains('- Package path: [${package.path}](${package.path})'),
    );
  }
  expect(content, isNot(contains(package.version)));
  expect(content, isNot(contains('3.35.8-ohos')));
  expect(content, isNot(contains('0.1.0')));
}

void _expectImplementationGuide(
  String content, {
  required List<_GuidancePackage> packages,
}) {
  _expectMarkdownHeadings(content, [
    '# FlutterOH Implementation',
    if (packages.length > 1) '## Packages',
    '## Metadata',
    '## Adaptation Checklist',
    '## Guardrails',
    '## Automatic Adaptation Command Flow',
    '## Platform Verification Matrix',
    '## Diagnostics Routing',
    '## Next Steps',
    '## Adaptation Workflow',
    '## Release Readiness',
    '## Completion Report',
    '## Local Commit Checkpoints',
    '## Before Commit',
  ]);
  _expectContainsAll(content, [
    'fluoh.yaml',
    'repository.git.url',
    'repository.git.branch',
    'upstream.git',
    'FLUOH_CHANGELOG.md',
    'fluoh help',
    'fluoh help package',
    'fluoh help verify',
    'Do not invent OHOS APIs',
    'destructive Git commands',
    'Preserve the local worktree',
    'fluoh doctor --project --json --strict',
    'fluoh deps get',
    'fluoh flutter analyze',
    'fluoh run ohos',
    'fluoh run android',
    'fluoh run ios',
    'fluoh run macos',
    'fluoh build linux',
    'fluoh run web',
    'fluoh build windows',
    'fluoh build ohos',
    '--no-codesign',
    '--device-id <id>',
    'integration_test/',
    'AI-assisted interaction evidence',
    'manual-assisted tool-readable evidence',
    'launch-only session state',
    '.fluoh/scenarios',
    'Flutter debug',
    'details.vmServiceUri',
    '--session-file <path>',
    'flutterRunSession',
    'inspect_session.py',
    'fluoh attach <platform>',
    'widget/component',
    'semantic',
    'screenshot recognition',
    'UI appearance',
    'No interaction required',
    'permission grant and denial',
    'Run smoke is not enough',
    'integration-test loop',
    '\$FLUOH_HOME/cache/package-runs',
    '--auto-sign',
    '--json',
    'nextCommand',
    'diagnostics',
    'Final report and release gate',
    'python3 <skill-dir>/scripts/check_report.py <report-path>',
    'Device-only behavior',
    'skipped with blocker',
    'maintainer-decision blocker',
    'stdoutTail',
    'ohos.signing_profile_failed',
    'ohos.direct_sign_failed',
    'android.apk_build_failed',
    'android.device_missing',
    'android.run_failed',
    'android.runtime_crash',
    'android.integration_test_failed',
    'ios.build_failed',
    'ios.device_missing',
    'ios.run_failed',
    'ios.runtime_crash',
    'ios.integration_test_failed',
    'macos.build_failed',
    'macos.device_missing',
    'macos.run_failed',
    'macos.runtime_crash',
    'macos.integration_test_failed',
    'linux.build_failed',
    'web.build_failed',
    'windows.build_failed',
    'ohos.runtime_crash',
    'ohos.install_failed',
    '.fluoh/reports/',
    'report-<timestamp>.md',
    'Release recommendation:',
    'changed files',
    'build, run, integration-test',
    'ignored local state',
    'git status --short --ignored=matching',
    'git config --local --get user.name',
    '--git-author-name',
    'approved adaptation scope authorizes small local checkpoint commits',
    'git diff --cached',
    'delivery report handoff',
    'implementation checkpoint',
    'release metadata checkpoint',
  ]);
  if (packages.length > 1) {
    _expectContainsAll(content, [
      'package',
      'fluoh verify --package <name>',
      'fluoh package release --package <name>',
    ]);
  }

  for (final package in packages) {
    _expectContainsAll(content, [
      package.name,
      package.examplePath,
      package.verifyCommand,
      package.versionCommand,
      package.releaseCommand,
    ]);
    if (packages.length > 1) {
      expect(content, contains(package.version));
    }
    if (package.path != '.') {
      expect(content, contains(package.path));
    } else {
      expect(content, contains('package'));
    }
  }
}

void _expectAgentsInstructions(
  String content, {
  required List<_GuidancePackage> packages,
}) {
  _expectMarkdownHeadings(content, [
    '# AGENTS.md',
    '## FlutterOH/OHOS Adaptation',
  ]);
  _expectContainsAll(content, [
    'For FlutterOH/OHOS package adaptation tasks, follow `FLUOH.md`.',
    'primary repository rules',
    'workflow, verification, release evidence, and handoff',
  ]);
  if (packages.length > 1) {
    _expectContainsAll(content, [
      '- Current packages:',
      for (final package in packages) '`${package.name}`',
    ]);
  } else {
    expect(content, contains('- Current package: `${packages.single.name}`.'));
  }

  expect(content, isNot(contains('## Working Rules')));
  expect(content, isNot(contains('## Automatic Adaptation Command Flow')));
  expect(content, isNot(contains('## Platform Verification Matrix')));
  expect(content, isNot(contains('## Diagnostics Routing')));
  expect(content, isNot(contains('## Completion Report')));
  expect(content, isNot(contains('## Local Commit Checkpoints')));
  expect(content, isNot(contains('fluoh doctor --project --json --strict')));
  expect(content, isNot(contains('fluoh run ohos')));
  expect(content, isNot(contains('.fluoh/reports/')));
}

void _expectChangelogEntry(String content, String tag) {
  final heading = '## $tag';
  final start = content.indexOf(heading);
  expect(start, isNot(-1), reason: 'Expected changelog entry $heading.');

  final next = content.indexOf('\n## ', start + heading.length);
  final entry = content
      .substring(start + heading.length, next == -1 ? content.length : next)
      .trim();
  expect(entry, isNotEmpty);
  expect(entry.split('\n').any((line) => line.trim().startsWith('- ')), isTrue);
}

void _expectMarkdownHeadings(String content, Iterable<String> expected) {
  final headings = content
      .split('\n')
      .where((line) => line.startsWith('#'))
      .toSet();
  for (final heading in expected) {
    expect(headings, contains(heading), reason: 'Missing heading $heading.');
  }
}

void _expectContainsAll(String content, Iterable<String> expected) {
  for (final value in expected) {
    expect(content, contains(value), reason: 'Expected to find "$value".');
  }
}

void _expectWrappedContainsAll(String content, Iterable<String> expected) {
  final normalizedContent = _normalizeOutput(content);
  for (final value in expected) {
    expect(
      normalizedContent,
      contains(_normalizeOutput(value)),
      reason: 'Expected to find "$value".',
    );
  }
}

String _normalizeOutput(String value) {
  return value
      .replaceAll(RegExp(r'(?<=[/-])\s+'), '')
      .replaceAll(RegExp(r'\s+'), ' ')
      .trim();
}

Future<void> _addWorkspacePackage(
  Directory repository, {
  required String path,
  required String name,
  required String version,
}) async {
  final package = Directory('${repository.path}/$path');
  await package.create(recursive: true);
  await File('${package.path}/pubspec.yaml').writeAsString('''
name: $name
version: $version

environment:
  sdk: ^3.0.0
''');
  await runGit(repository, ['add', path]);
  await runGit(repository, ['commit', '-m', 'Add $name fixture']);
}

Future<void> _addWorkspaceFlutterPackage(
  Directory repository, {
  required String path,
  required String name,
  required String version,
}) async {
  final package = Directory('${repository.path}/$path');
  await Directory('${package.path}/lib').create(recursive: true);
  await Directory('${package.path}/example/lib').create(recursive: true);
  await File('${package.path}/pubspec.yaml').writeAsString('''
name: $name
version: $version

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
''');
  await File(
    '${package.path}/lib/$name.dart',
  ).writeAsString('library $name;\n');
  await File('${package.path}/example/pubspec.yaml').writeAsString('''
name: ${name}_example

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  $name:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
''');
  await File('${package.path}/example/lib/main.dart').writeAsString('''
import 'package:flutter/widgets.dart';

void main() {
  runApp(const Placeholder());
}
''');
  await runGit(repository, ['add', path]);
  await runGit(repository, ['commit', '-m', 'Add $name Flutter fixture']);
}

Future<Directory> _createPackageCreateSdkSource(
  Directory parent, {
  required String logName,
  String? requiredCreateOrg,
}) async {
  final source = Directory('${parent.path}/flutter_sdk_source_$logName');
  final sdkRepository = Directory('${parent.path}/flutter_sdk_$logName');
  await sdkRepository.create(recursive: true);
  await _runProcess('git', ['init', '--initial-branch=main'], sdkRepository);
  await _runProcess('git', [
    'config',
    'user.email',
    'fixture@example.com',
  ], sdkRepository);
  await _runProcess('git', ['config', 'user.name', 'Fixture'], sdkRepository);
  final flutter = File('${sdkRepository.path}/bin/flutter');
  await flutter.parent.create(recursive: true);
  await flutter.writeAsString(
    _fakeFlutterScript(
      '${parent.path}/$logName',
      requiredCreateOrg: requiredCreateOrg,
    ),
  );
  await _runProcess('chmod', ['+x', flutter.path], sdkRepository);
  await File('${sdkRepository.path}/README.md').writeAsString('# SDK\n');
  await _runProcess('git', ['add', '.'], sdkRepository);
  await _runProcess('git', ['commit', '-m', 'Initial SDK'], sdkRepository);
  await _runProcess('git', ['tag', '3.35.8-ohos-0.0.3'], sdkRepository);
  await writeSdkSourceFixture(
    source,
    sdkRepository: sdkRepository.path,
    releases: {'3.35.8-ohos-0.0.3': 'stable'},
  );
  return source;
}

String _fakeFlutterScript(String logPath, {String? requiredCreateOrg}) {
  final requiredOrg = requiredCreateOrg ?? '';
  return '''
#!/bin/sh
printf "%s::%s\\n" "\$(pwd)" "\$*" >> "$logPath"
if [ "\$1" = "create" ]; then
  printf "flutter create stdout\\n"
  printf "flutter create stderr\\n" >&2
  target=""
  platforms=""
  org=""
  while [ "\$#" -gt 0 ]; do
    case "\$1" in
      --platforms=*) platforms="\${1#--platforms=}" ;;
      --org=*) org="\${1#--org=}" ;;
      --org) shift; org="\$1" ;;
      --project-name) shift ;;
      --no-pub) ;;
      create) ;;
      *) target="\$1" ;;
    esac
    shift
  done
  if [ "$requiredOrg" != "" ] && [ "\$org" != "$requiredOrg" ]; then
    printf "expected --org $requiredOrg, got %s\\n" "\$org" >&2
    exit 64
  fi
  mkdir -p "\$target/lib"
  old_ifs="\$IFS"
  IFS=,
  for platform in \$platforms; do
    mkdir -p "\$target/\$platform"
    printf "{}\\n" > "\$target/\$platform/build-profile.json5"
  done
  IFS="\$old_ifs"
fi
exit 0
''';
}

Future<void> _addAmbiguousExampleOrganizations(Directory repo) async {
  await Directory(
    '${repo.path}/example/android/app/src/main',
  ).create(recursive: true);
  await File(
    '${repo.path}/example/android/app/src/main/AndroidManifest.xml',
  ).writeAsString('''
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="io.flutter.plugins.cameraExample">
</manifest>
''');
  await Directory(
    '${repo.path}/example/ios/Runner.xcodeproj',
  ).create(recursive: true);
  await File(
    '${repo.path}/example/ios/Runner.xcodeproj/project.pbxproj',
  ).writeAsString('''
{
  PRODUCT_BUNDLE_IDENTIFIER = dev.flutter.plugins.cameraExample;
}
''');
  await _runProcess('git', ['add', '.'], repo);
  await _runProcess('git', [
    'commit',
    '-m',
    'Add example platform metadata',
  ], repo);
}

Future<Directory> _createUpstreamFlutterPluginRepository(Directory repo) async {
  await repo.create(recursive: true);
  await _runProcess('git', ['init', '--initial-branch=main'], repo);
  await _runProcess('git', [
    'config',
    'user.email',
    'fixture@example.com',
  ], repo);
  await _runProcess('git', ['config', 'user.name', 'Fixture'], repo);
  await Directory('${repo.path}/lib').create(recursive: true);
  await Directory('${repo.path}/example/lib').create(recursive: true);
  await File('${repo.path}/lib/camera.dart').writeAsString('library camera;\n');
  await File('${repo.path}/pubspec.yaml').writeAsString('''
name: camera
version: 0.11.0

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.flutter.camera
        pluginClass: CameraPlugin
      ios:
        pluginClass: CameraPlugin
''');
  await File('${repo.path}/example/pubspec.yaml').writeAsString('''
name: camera_example

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  camera:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
''');
  await File('${repo.path}/example/lib/main.dart').writeAsString('''
import 'package:flutter/widgets.dart';

void main() {
  runApp(const Placeholder());
}
''');
  await File('${repo.path}/LICENSE').writeAsString(_testLicenseContent);
  await _runProcess('git', ['add', '.'], repo);
  await _runProcess('git', ['commit', '-m', 'Initial Flutter plugin'], repo);
  return repo;
}

Future<Directory> _createFederatedWorkspaceRepository(Directory repo) async {
  await repo.create(recursive: true);
  await _runProcess('git', ['init', '--initial-branch=main'], repo);
  await _runProcess('git', [
    'config',
    'user.email',
    'fixture@example.com',
  ], repo);
  await _runProcess('git', ['config', 'user.name', 'Fixture'], repo);
  await _writeFederatedPackage(
    repo,
    path: 'packages/path_provider/path_provider',
    name: 'path_provider',
    version: '2.1.0',
    defaultPackages: const {
      'android': 'path_provider_android',
      'ios': 'path_provider_foundation',
    },
  );
  await _writePlainPackage(
    repo,
    path: 'packages/path_provider/path_provider_android',
    name: 'path_provider_android',
    version: '2.1.0',
  );
  await _writePlainPackage(
    repo,
    path: 'packages/path_provider/path_provider_foundation',
    name: 'path_provider_foundation',
    version: '2.1.0',
  );
  await File('${repo.path}/README.md').writeAsString('# federated workspace\n');
  await File('${repo.path}/LICENSE').writeAsString(_testLicenseContent);
  await _runProcess('git', ['add', '.'], repo);
  await _runProcess('git', [
    'commit',
    '-m',
    'Initial federated workspace',
  ], repo);
  return repo;
}

Future<void> _writeFederatedPackage(
  Directory repo, {
  required String path,
  required String name,
  required String version,
  required Map<String, String> defaultPackages,
}) async {
  final directory = Directory('${repo.path}/$path');
  await Directory('${directory.path}/lib').create(recursive: true);
  final platforms = defaultPackages.entries.map((entry) {
    return '''
      ${entry.key}:
        default_package: ${entry.value}
''';
  }).join();
  await File('${directory.path}/pubspec.yaml').writeAsString('''
name: $name
version: $version

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
$platforms
''');
  await File(
    '${directory.path}/lib/$name.dart',
  ).writeAsString('library $name;\n');
}

Future<void> _writePlainPackage(
  Directory repo, {
  required String path,
  required String name,
  required String version,
}) async {
  final directory = Directory('${repo.path}/$path');
  await Directory('${directory.path}/lib').create(recursive: true);
  await File('${directory.path}/pubspec.yaml').writeAsString('''
name: $name
version: $version

environment:
  sdk: ^3.0.0
''');
  await File(
    '${directory.path}/lib/$name.dart',
  ).writeAsString('library $name;\n');
}

const _testLicenseContent = '''
MIT License

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software.
''';

Future<void> _runProcess(
  String executable,
  List<String> arguments,
  Directory workingDirectory,
) async {
  final result = await Process.run(
    executable,
    arguments,
    workingDirectory: workingDirectory.path,
  );
  if (result.exitCode != 0) {
    fail('$executable ${arguments.join(' ')} failed:\n${result.stderr}');
  }
}
