part of 'package_repository_docs.dart';

/// Returns the separator needed before appending generated Markdown content.
String markdownAppendSeparator(String content) {
  if (content.endsWith('\n\n')) {
    return '';
  }
  if (content.endsWith('\n')) {
    return '\n';
  }
  return '\n\n';
}

const _implementationGuideSectionId = 'package-implementation-guide';
const _agentsInstructionsSectionId = 'package-agents-instructions';
const _readmeAdaptationSectionId = 'package-readme-adaptation';

bool _generatedSectionOwnsFile(String? existing, {required String sectionId}) {
  if (existing == null || existing.trim().isEmpty) {
    return true;
  }
  return _contentWithoutGeneratedSection(
    existing,
    sectionId: sectionId,
  ).trim().isEmpty;
}

String _contentWithGeneratedSection(
  String? existing,
  String generated, {
  required String sectionId,
  required int templateVersion,
}) {
  final block = _generatedSectionBlock(
    generated,
    sectionId: sectionId,
    templateVersion: templateVersion,
  );
  if (existing == null || existing.trim().isEmpty) {
    return block;
  }

  final replaced = _replaceGeneratedSection(
    existing,
    block,
    sectionId: sectionId,
  );
  if (replaced != null) {
    return replaced;
  }

  return '$existing${markdownAppendSeparator(existing)}$block';
}

String _contentWithReadmeGeneratedSection(
  String? existing,
  String generated, {
  required String sectionId,
  required int templateVersion,
  required String fallbackTitle,
}) {
  final block = _generatedSectionBlock(
    generated,
    sectionId: sectionId,
    templateVersion: templateVersion,
  );
  if (existing == null || existing.trim().isEmpty) {
    return '$block\n# $fallbackTitle\n';
  }

  final content = _contentWithoutGeneratedSection(
    existing,
    sectionId: sectionId,
  );
  if (content.trim().isEmpty) {
    return '$block\n# $fallbackTitle\n';
  }
  return '$block${content.startsWith('\n') ? '' : '\n'}$content';
}

String _generatedSectionBlock(
  String content, {
  required String sectionId,
  required int templateVersion,
}) {
  final normalized = content.endsWith('\n') ? content : '$content\n';
  return '${_generatedSectionStart(sectionId, templateVersion)}\n'
      '<!-- This section is generated by fluoh. Do not edit inside this block; '
      'run `fluoh package docs refresh` after updating fluoh.yaml or upgrading '
      'fluoh. -->\n'
      '$normalized${_generatedSectionEnd(sectionId)}\n';
}

String _generatedSectionStart(String sectionId, int templateVersion) =>
    '<!-- fluoh:generated:start id=$sectionId template=$templateVersion -->';

String _generatedSectionEnd(String sectionId) =>
    '<!-- fluoh:generated:end id=$sectionId -->';

String? _replaceGeneratedSection(
  String content,
  String replacement, {
  required String sectionId,
}) {
  final match = _findGeneratedSection(content, sectionId: sectionId);
  if (match == null) {
    return null;
  }
  final afterEnd = match.end + match.endMarker.length;
  final suffixStart =
      afterEnd < content.length && content.codeUnitAt(afterEnd) == 10
      ? afterEnd + 1
      : afterEnd;
  return '${content.substring(0, match.start)}$replacement'
      '${content.substring(suffixStart)}';
}

String _contentWithoutGeneratedSection(
  String content, {
  required String sectionId,
}) {
  final match = _findGeneratedSection(content, sectionId: sectionId);
  if (match == null) {
    return content;
  }
  final afterEnd = match.end + match.endMarker.length;
  final suffixStart =
      afterEnd < content.length && content.codeUnitAt(afterEnd) == 10
      ? afterEnd + 1
      : afterEnd;
  return '${content.substring(0, match.start)}${content.substring(suffixStart)}';
}

_GeneratedSectionMatch? _findGeneratedSection(
  String content, {
  required String sectionId,
}) {
  final startPattern = RegExp(
    '<!-- fluoh:generated:start id=${RegExp.escape(sectionId)} '
    r'template=\d+ -->',
  );
  final startMatch = startPattern.firstMatch(content);
  if (startMatch != null) {
    final endMarker = _generatedSectionEnd(sectionId);
    final end = content.indexOf(endMarker, startMatch.end);
    if (end >= 0) {
      return _GeneratedSectionMatch(
        start: startMatch.start,
        end: end,
        endMarker: endMarker,
      );
    }
  }
  return null;
}

class _GeneratedSectionMatch {
  const _GeneratedSectionMatch({
    required this.start,
    required this.end,
    required this.endMarker,
  });

  final int start;
  final int end;
  final String endMarker;
}
